### ISSUE TITLE
Creating a paged gui with VirtualInventory inside it

### ISSUE THREAD

**Issue by BlackBaroness** [NichtStudioCode/InvUI#100]
Hi there. Looks like there is no way to create a PagedGui what will show VirtualInventory, so there is no way to create paged interactable inventories, even while the VirtualInventory itself supports creating inventories much bigger than vanilla ones. I think it's a big omission.

I saw the #43, but it's quite complex and not portable to implement our own solution instead of using a default one. Can you implement this feature in InvUI, please? I believe a lot of people would like to see it.

**Comment by NichtStudioCode** [comment]
This functionality was already added [1.17](https://github.com/NichtStudioCode/InvUI/releases/tag/1.17)
