### ISSUE TITLE
InvUI pom.xml Invalid

### ISSUE THREAD

**Issue by ZenoCoding** [NichtStudioCode/InvUI#11]
I'm getting this error when building my plugin:

Invalid POM for <invui>, transitive dependencies (if any) will not be available, enable debug logging for more details 

In my case, my machine builds the plugin just fine due to transitive dependencies being stored in a cache.

However, on any other machine, this becomes a problem as there is no current cache for transitive dependencies such as de.studiocode.inventoryaccess.

If you could help me with this in any way that would be of great help.

**Comment by NichtStudioCode** [comment]
The repo url defined [here](https://github.com/ZenoCoding/SuperItems/blob/main/pom.xml#L84) is wrong. `https://repo.xenondevs.xyz/releases` would be correct.

**Comment by ZenoCoding** [comment]
I've since resolved the issue on GitHub actions (Shown on the attribute branch through my latest commit), yet the issue persists on other devices. I've tried deleting the local cache for the library and re-syncing/indexing maven, but to no avail. 

Is this still an issue with my pom.xml? Or are there still residual corrupt files on my other machine?
