### ISSUE TITLE
Repository URL is incorrect

### ISSUE THREAD

**Issue by ItsRainingHP** [NichtStudioCode/InvUI#17]
In order for me to utilize your API. I actually had to go to your repository (which really was not easy to find - I suggest a URL on your readme in Github) to find it. I am impressed with your documentation and I am excited to try your API in the plugin I am currently developing. I used:
https://repo.xenondevs.xyz/#/releases

**Comment by NichtStudioCode** [comment]
?

![](https://i.imgur.com/wlXRrqn.png)
![](https://i.imgur.com/nFTNKg7.png)

**Comment by ItsRainingHP** [comment]
Have yiu tried to import your project using Maven or even used your link or checked it? If you go to https://repo.xenondevs.xyz/releases you will get a 404 and Maven fails to find the repo. You have to add the # like so https://repo.xenondevs.xyz/#/releases

**Comment by NichtStudioCode** [comment]
Yes...? The dashboard is under https://repo.xenondevs.xyz/#/releases. Maven obviously doesn't access a GUI in order to download stuff?

**Comment by ItsRainingHP** [comment]
> Yes...? The dashboard is under https://repo.xenondevs.xyz/#/releases. Maven obviously doesn't access a GUI in order to download stuff?

I understand it does not use the GUI. I am telling you when I use your repo link with version 0.10.2, Maven fails to locate the source without adding "#". Why not try it on the compiler to confirm yourself instead of just not believing me.

**Comment by NichtStudioCode** [comment]
https://repo.xenondevs.xyz/releases/de/studiocode/invui/InvUI/0.10.2/InvUI-0.10.2.jar

**Comment by ItsRainingHP** [comment]
> https://repo.xenondevs.xyz/releases/de/studiocode/invui/InvUI/0.10.2/InvUI-0.10.2.jar

Can you test in the compiler? Intellij Literally fails to find your repo unless I add the #.  If it works for everyone else fine I guess I am the outlier.

**Comment by NichtStudioCode** [comment]
I have. I'm using InvUI in other projects. Try removing InvUI from your local repository and then reloading maven.

**Comment by ItsRainingHP** [comment]
Okay wow thanks! I deleted my entire repository folder for intellij and invalidated caches. Now your repo loads. Couple things while I have you online. 1) Do you add a scope to your repo? When I do not, it adds the entire shaded jar to my project. When I add a provided scope, the plugin fails with NoClassDefFound error. 2) Do you have a support discord?

**Comment by NichtStudioCode** [comment]
Yes, you will need to include InvUI in your jar unless you have your own library loading system in place. You cannot use Spigot's library loader because InvUI is currently not on the central repository. When you set the [dependency scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope) to provided, you tell Maven that InvUI's classes will already be present at runtime (which they're not) and Maven Shade will not include them in the jar.

[Yes, we have a discord](https://discord.gg/Xu86AXdNwp)

**Comment by ItsRainingHP** [comment]
You are the man thank you! Will recommend your repo to others.
