### ISSUE TITLE
Artifact group is different in the README and docs site

### ISSUE THREAD

**Issue by lMartin3** [NichtStudioCode/InvUI#20]
In [line 38 of the README](https://github.com/NichtStudioCode/InvUI/blame/main/README.md#L38) the package is set to `xyz.xenondevs.invui` while in the [official documentation](https://xenondevs.xyz/docs/invui/) it is set to `de.studiocode.invui`
![image](https://user-images.githubusercontent.com/38576621/215563263-011543ec-e3cf-4fc9-bb36-e4ad7ce5722a.png)

This is an issue since the latest version in `xyz.xenondevs.invui` is `1.0-SNAPSHOT` while in`de.studiocode.invui` it is `0.10.2`

btw, please consider adding a version badge to the readme to make things easier

**Comment by NichtStudioCode** [comment]
fixed
