### ISSUE TITLE
Support for platforms other than Bukkit

### ISSUE THREAD

**Issue by MelonHell** [NichtStudioCode/InvUI#29]
I think InvUI is the best library for creating a serverside gui in minecraft, I would really like to use it for example in Minestom.

If you plan to somehow radically change the library, I would very much like the platform code to be separated from the api code

**Comment by NichtStudioCode** [comment]
Thanks for your feedback, but this would require rewriting most parts of the library (because basically everything works around Bukkit's implementations), so it's probably something that I'll do in the near future, if ever.
