### ISSUE TITLE
expose gui instance on click event handler for items.

### ISSUE THREAD

**Issue by portlek** [NichtStudioCode/InvUI#34]
i want to be able to remove an item from a scroll gui when i click an item where's in the content itself. but i don't have access to gui instance while the player clicking the item.

[here](https://github.com/NichtStudioCode/InvUI/blob/main/invui-core/src/main/java/xyz/xenondevs/invui/gui/AbstractGui.java#L69)

**Comment by NichtStudioCode** [comment]
Hi, InvUI is designed in a way that `Item`s are generally not aware of the Gui they're placed in. You can use `ControlItem`s, which are an exception to that rule. Otherwise, store the Gui instance somewhere else.
