### ISSUE TITLE
How to combine PagedGui with VirtualInventory

### ISSUE THREAD

**Issue by ShellWen** [NichtStudioCode/InvUI#39]
It seems that adding VirtualInventory as an Ingredient doesn't work, and the only method available for PagedGui is setContent.

I'm really eager to figure out how to combine PagedGui and VirtualInventory effectively to enable page-by-page browsing of VirtualInventory. Any assistance or guidance would be greatly appreciated!

**Comment by NichtStudioCode** [comment]
There is currently no PagedGUI implementation that accepts Inventories as content type

**Comment by ShellWen** [comment]
> There is currently no PagedGUI implementation that accepts Inventories as content type

It means I need impl it myself? Is PR welcomed?

**Comment by NichtStudioCode** [comment]
Added in v1.13
