### ISSUE TITLE
NoClassDefFoundError: xyz/xenondevs/invui/item/ItemProvider on Spigot 1.20

### ISSUE THREAD

**Issue by shradinx** [NichtStudioCode/InvUI#55]
I received a ClassNotFoundException in my server console upon loading my plugin. The full console error, my plugin code, and the repositories + dependencies section of my build.gradle have been linked below. Any ideas as to why the plugin is not loading? It loads fine when I comment out the code containing the InvUI API.

Server is Spigot 1.20, and I am using InvUI 1.23

![image](https://github.com/NichtStudioCode/InvUI/assets/107893057/52a0f4fa-0818-4ee3-8d2c-9a4bcdb9eae1)
![image](https://github.com/NichtStudioCode/InvUI/assets/107893057/7f23c015-3bc0-4b72-896a-c7b440123c26)
![image](https://github.com/NichtStudioCode/InvUI/assets/107893057/40b6122c-eb3d-4579-bb5f-6c32d83c05d2)

**Comment by xGlenor** [comment]
@shradinx  Hi, how did you fix it?
