### ISSUE TITLE
Erorr when enable my plugin with invui

### ISSUE THREAD

**Issue by rageyh** [NichtStudioCode/InvUI#60]
I'm using the Invui library and when I try to create an item with ItemBuilder it gives me this error, what can I do?

![image](https://github.com/NichtStudioCode/InvUI/assets/48997749/3c319ef2-2cf9-438a-a114-04365885fc3f)

**Comment by NichtStudioCode** [comment]
Are you using gradle shadow's `minimize()`? If so, don't.

**Comment by rageyh** [comment]
oh ok, thats work. thanks

**Comment by rageyh** [comment]
there is another small bug, when there is a split window open in a player and the server stops with the inventory open, this causes the gui elements to remain below the player as if not deleting them.

**Comment by NichtStudioCode** [comment]
Please create a separate issue for that
