### ISSUE TITLE
Error when use SkullBuilder(uuid)

### ISSUE THREAD

**Issue by rageyh** [NichtStudioCode/InvUI#61]
![image](https://github.com/NichtStudioCode/InvUI/assets/48997749/07d90110-4227-4679-a822-c474a2ac55df)
![image](https://github.com/NichtStudioCode/InvUI/assets/48997749/8fd9e447-f593-4741-9664-b219d62f7573)

(Server is on offline mode)

**Comment by NichtStudioCode** [comment]
The offline-mode UUID has no Minecraft account associated with it, and therefore also no skin.
