### ISSUE TITLE
Adding api to the server?

### ISSUE THREAD

**Issue by GustavHaavik** [NichtStudioCode/InvUI#72]
I have added the repository and dependency to my pom.xml 
```
<repositories>
        <repository>
            <id>xenondevs</id>
            <url>https://repo.xenondevs.xyz/releases</url>
        </repository>
    </repositories>
```
```
<dependencies>
        <dependency>
            <groupId>xyz.xenondevs.invui</groupId>
            <artifactId>invui</artifactId>
            <version>1.32</version>
            <type>pom</type>
        </dependency>
    </dependencies>
```

but it doesnt compile the code into my plugin's jar file, so I get a `NoClassDefFoundError: xyz/xenondevs/invui/item/Item`.

**Comment by NichtStudioCode** [comment]
You can create a fat jar using maven shade, or load the library any other way, for example using Paper's library loading mechanism.
