### ISSUE TITLE
OutsideClickHandler not working

### ISSUE THREAD

**Issue by Nononitas** [NichtStudioCode/InvUI#86]
OutsideClickHandler are never getting fired.
I registered one like this:
![grafik](https://github.com/user-attachments/assets/e857c460-7968-43e3-966a-41b8f56e2ba2)

The Consumer with the event however only gets fired when click not on any Inventory Slot. Shouldn't be the behaivour in this way that you can register a global click handler, for the window?

**Comment by NichtStudioCode** [comment]
The **outside** click handlers are only called when clicking **outside** the inventory. All other clicks are handled by the clicked slot element (item / virtual inventory)

**Comment by Nononitas** [comment]
How can you handle clicks outside of the window then? I want to be able to interact with the lower Inventory, without filling it?

**Comment by NichtStudioCode** [comment]
There's currently no way to listen to clicks on slots that aren't actually part of the Window, but you can just listen to the `InventoryClickEvent` and get the currently open window using `WindowManager`.
