### ISSUE TITLE
[1.21.1] Unable to use SkullBuilder

### ISSUE THREAD

**Issue by ineanto** [NichtStudioCode/InvUI#91]
Hello, hope you're doing great.

Trying to use the ```SkullBuilder``` class using InvUI v1.37 (and 1.36, I tested both) results in the following error : 
```java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile```

Do you have any clue as why this happens? Thank you in any case.

Environment:
1.  Paper Server + API (v1.21.1)
2. InvUI (v1.37)

**Comment by ineanto** [comment]
Unable to test right now but might be caused by conflicting mappings between server and plugin?

**Comment by rexlManu** [comment]
It's the same issue, profile was replaced in build 83 paper 1.21.1
https://github.com/CryptoMorin/XSeries/pull/299
